tp_stampar:
    resource: "@TpStamparBundle/Controller/"
    type:     annotation
    prefix:   /stampar

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
