parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: tpbd
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6f71df104b359a5a1b4110dd8aab66dc35
    database_path: null
